// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: res/pc.proto

public final class Pc {
  private Pc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PatientCaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PatientCase)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int32 ageYears = 2;</code>
     * @return The ageYears.
     */
    int getAgeYears();

    /**
     * <code>int32 ageDays = 3;</code>
     * @return The ageDays.
     */
    int getAgeDays();

    /**
     * <code>uint32 birthDate = 4;</code>
     * @return The birthDate.
     */
    int getBirthDate();

    /**
     * <code>uint32 admDate = 5;</code>
     * @return The admDate.
     */
    int getAdmDate();

    /**
     * <code>uint32 sepDate = 6;</code>
     * @return The sepDate.
     */
    int getSepDate();

    /**
     * <code>int32 leaveDays = 7;</code>
     * @return The leaveDays.
     */
    int getLeaveDays();

    /**
     * <code>string sex = 8;</code>
     * @return The sex.
     */
    java.lang.String getSex();
    /**
     * <code>string sex = 8;</code>
     * @return The bytes for sex.
     */
    com.google.protobuf.ByteString
        getSexBytes();

    /**
     * <code>string adm = 9;</code>
     * @return The adm.
     */
    java.lang.String getAdm();
    /**
     * <code>string adm = 9;</code>
     * @return The bytes for adm.
     */
    com.google.protobuf.ByteString
        getAdmBytes();

    /**
     * <code>string sep = 10;</code>
     * @return The sep.
     */
    java.lang.String getSep();
    /**
     * <code>string sep = 10;</code>
     * @return The bytes for sep.
     */
    com.google.protobuf.ByteString
        getSepBytes();

    /**
     * <code>int32 gestage = 11;</code>
     * @return The gestage.
     */
    int getGestage();

    /**
     * <code>int32 los = 12;</code>
     * @return The los.
     */
    int getLos();

    /**
     * <code>int32 hmv = 13;</code>
     * @return The hmv.
     */
    int getHmv();

    /**
     * <code>bool bh = 14;</code>
     * @return The bh.
     */
    boolean getBh();
  }
  /**
   * Protobuf type {@code PatientCase}
   */
  public static final class PatientCase extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PatientCase)
      PatientCaseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PatientCase.newBuilder() to construct.
    private PatientCase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PatientCase() {
      id_ = "";
      sex_ = "";
      adm_ = "";
      sep_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PatientCase();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PatientCase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              ageYears_ = input.readInt32();
              break;
            }
            case 24: {

              ageDays_ = input.readInt32();
              break;
            }
            case 32: {

              birthDate_ = input.readUInt32();
              break;
            }
            case 40: {

              admDate_ = input.readUInt32();
              break;
            }
            case 48: {

              sepDate_ = input.readUInt32();
              break;
            }
            case 56: {

              leaveDays_ = input.readInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              sex_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              adm_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              sep_ = s;
              break;
            }
            case 88: {

              gestage_ = input.readInt32();
              break;
            }
            case 96: {

              los_ = input.readInt32();
              break;
            }
            case 104: {

              hmv_ = input.readInt32();
              break;
            }
            case 112: {

              bh_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Pc.internal_static_PatientCase_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Pc.internal_static_PatientCase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Pc.PatientCase.class, Pc.PatientCase.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGEYEARS_FIELD_NUMBER = 2;
    private int ageYears_;
    /**
     * <code>int32 ageYears = 2;</code>
     * @return The ageYears.
     */
    @java.lang.Override
    public int getAgeYears() {
      return ageYears_;
    }

    public static final int AGEDAYS_FIELD_NUMBER = 3;
    private int ageDays_;
    /**
     * <code>int32 ageDays = 3;</code>
     * @return The ageDays.
     */
    @java.lang.Override
    public int getAgeDays() {
      return ageDays_;
    }

    public static final int BIRTHDATE_FIELD_NUMBER = 4;
    private int birthDate_;
    /**
     * <code>uint32 birthDate = 4;</code>
     * @return The birthDate.
     */
    @java.lang.Override
    public int getBirthDate() {
      return birthDate_;
    }

    public static final int ADMDATE_FIELD_NUMBER = 5;
    private int admDate_;
    /**
     * <code>uint32 admDate = 5;</code>
     * @return The admDate.
     */
    @java.lang.Override
    public int getAdmDate() {
      return admDate_;
    }

    public static final int SEPDATE_FIELD_NUMBER = 6;
    private int sepDate_;
    /**
     * <code>uint32 sepDate = 6;</code>
     * @return The sepDate.
     */
    @java.lang.Override
    public int getSepDate() {
      return sepDate_;
    }

    public static final int LEAVEDAYS_FIELD_NUMBER = 7;
    private int leaveDays_;
    /**
     * <code>int32 leaveDays = 7;</code>
     * @return The leaveDays.
     */
    @java.lang.Override
    public int getLeaveDays() {
      return leaveDays_;
    }

    public static final int SEX_FIELD_NUMBER = 8;
    private volatile java.lang.Object sex_;
    /**
     * <code>string sex = 8;</code>
     * @return The sex.
     */
    @java.lang.Override
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sex_ = s;
        return s;
      }
    }
    /**
     * <code>string sex = 8;</code>
     * @return The bytes for sex.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADM_FIELD_NUMBER = 9;
    private volatile java.lang.Object adm_;
    /**
     * <code>string adm = 9;</code>
     * @return The adm.
     */
    @java.lang.Override
    public java.lang.String getAdm() {
      java.lang.Object ref = adm_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        adm_ = s;
        return s;
      }
    }
    /**
     * <code>string adm = 9;</code>
     * @return The bytes for adm.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAdmBytes() {
      java.lang.Object ref = adm_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEP_FIELD_NUMBER = 10;
    private volatile java.lang.Object sep_;
    /**
     * <code>string sep = 10;</code>
     * @return The sep.
     */
    @java.lang.Override
    public java.lang.String getSep() {
      java.lang.Object ref = sep_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sep_ = s;
        return s;
      }
    }
    /**
     * <code>string sep = 10;</code>
     * @return The bytes for sep.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSepBytes() {
      java.lang.Object ref = sep_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sep_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GESTAGE_FIELD_NUMBER = 11;
    private int gestage_;
    /**
     * <code>int32 gestage = 11;</code>
     * @return The gestage.
     */
    @java.lang.Override
    public int getGestage() {
      return gestage_;
    }

    public static final int LOS_FIELD_NUMBER = 12;
    private int los_;
    /**
     * <code>int32 los = 12;</code>
     * @return The los.
     */
    @java.lang.Override
    public int getLos() {
      return los_;
    }

    public static final int HMV_FIELD_NUMBER = 13;
    private int hmv_;
    /**
     * <code>int32 hmv = 13;</code>
     * @return The hmv.
     */
    @java.lang.Override
    public int getHmv() {
      return hmv_;
    }

    public static final int BH_FIELD_NUMBER = 14;
    private boolean bh_;
    /**
     * <code>bool bh = 14;</code>
     * @return The bh.
     */
    @java.lang.Override
    public boolean getBh() {
      return bh_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (ageYears_ != 0) {
        output.writeInt32(2, ageYears_);
      }
      if (ageDays_ != 0) {
        output.writeInt32(3, ageDays_);
      }
      if (birthDate_ != 0) {
        output.writeUInt32(4, birthDate_);
      }
      if (admDate_ != 0) {
        output.writeUInt32(5, admDate_);
      }
      if (sepDate_ != 0) {
        output.writeUInt32(6, sepDate_);
      }
      if (leaveDays_ != 0) {
        output.writeInt32(7, leaveDays_);
      }
      if (!getSexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, sex_);
      }
      if (!getAdmBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, adm_);
      }
      if (!getSepBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, sep_);
      }
      if (gestage_ != 0) {
        output.writeInt32(11, gestage_);
      }
      if (los_ != 0) {
        output.writeInt32(12, los_);
      }
      if (hmv_ != 0) {
        output.writeInt32(13, hmv_);
      }
      if (bh_ != false) {
        output.writeBool(14, bh_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (ageYears_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ageYears_);
      }
      if (ageDays_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ageDays_);
      }
      if (birthDate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, birthDate_);
      }
      if (admDate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, admDate_);
      }
      if (sepDate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, sepDate_);
      }
      if (leaveDays_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, leaveDays_);
      }
      if (!getSexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, sex_);
      }
      if (!getAdmBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, adm_);
      }
      if (!getSepBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, sep_);
      }
      if (gestage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, gestage_);
      }
      if (los_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, los_);
      }
      if (hmv_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, hmv_);
      }
      if (bh_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, bh_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Pc.PatientCase)) {
        return super.equals(obj);
      }
      Pc.PatientCase other = (Pc.PatientCase) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (getAgeYears()
          != other.getAgeYears()) return false;
      if (getAgeDays()
          != other.getAgeDays()) return false;
      if (getBirthDate()
          != other.getBirthDate()) return false;
      if (getAdmDate()
          != other.getAdmDate()) return false;
      if (getSepDate()
          != other.getSepDate()) return false;
      if (getLeaveDays()
          != other.getLeaveDays()) return false;
      if (!getSex()
          .equals(other.getSex())) return false;
      if (!getAdm()
          .equals(other.getAdm())) return false;
      if (!getSep()
          .equals(other.getSep())) return false;
      if (getGestage()
          != other.getGestage()) return false;
      if (getLos()
          != other.getLos()) return false;
      if (getHmv()
          != other.getHmv()) return false;
      if (getBh()
          != other.getBh()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + AGEYEARS_FIELD_NUMBER;
      hash = (53 * hash) + getAgeYears();
      hash = (37 * hash) + AGEDAYS_FIELD_NUMBER;
      hash = (53 * hash) + getAgeDays();
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthDate();
      hash = (37 * hash) + ADMDATE_FIELD_NUMBER;
      hash = (53 * hash) + getAdmDate();
      hash = (37 * hash) + SEPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getSepDate();
      hash = (37 * hash) + LEAVEDAYS_FIELD_NUMBER;
      hash = (53 * hash) + getLeaveDays();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex().hashCode();
      hash = (37 * hash) + ADM_FIELD_NUMBER;
      hash = (53 * hash) + getAdm().hashCode();
      hash = (37 * hash) + SEP_FIELD_NUMBER;
      hash = (53 * hash) + getSep().hashCode();
      hash = (37 * hash) + GESTAGE_FIELD_NUMBER;
      hash = (53 * hash) + getGestage();
      hash = (37 * hash) + LOS_FIELD_NUMBER;
      hash = (53 * hash) + getLos();
      hash = (37 * hash) + HMV_FIELD_NUMBER;
      hash = (53 * hash) + getHmv();
      hash = (37 * hash) + BH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBh());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Pc.PatientCase parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pc.PatientCase parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pc.PatientCase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pc.PatientCase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pc.PatientCase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pc.PatientCase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pc.PatientCase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Pc.PatientCase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Pc.PatientCase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Pc.PatientCase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Pc.PatientCase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Pc.PatientCase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Pc.PatientCase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PatientCase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PatientCase)
        Pc.PatientCaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Pc.internal_static_PatientCase_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Pc.internal_static_PatientCase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Pc.PatientCase.class, Pc.PatientCase.Builder.class);
      }

      // Construct using Pc.PatientCase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        ageYears_ = 0;

        ageDays_ = 0;

        birthDate_ = 0;

        admDate_ = 0;

        sepDate_ = 0;

        leaveDays_ = 0;

        sex_ = "";

        adm_ = "";

        sep_ = "";

        gestage_ = 0;

        los_ = 0;

        hmv_ = 0;

        bh_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Pc.internal_static_PatientCase_descriptor;
      }

      @java.lang.Override
      public Pc.PatientCase getDefaultInstanceForType() {
        return Pc.PatientCase.getDefaultInstance();
      }

      @java.lang.Override
      public Pc.PatientCase build() {
        Pc.PatientCase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Pc.PatientCase buildPartial() {
        Pc.PatientCase result = new Pc.PatientCase(this);
        result.id_ = id_;
        result.ageYears_ = ageYears_;
        result.ageDays_ = ageDays_;
        result.birthDate_ = birthDate_;
        result.admDate_ = admDate_;
        result.sepDate_ = sepDate_;
        result.leaveDays_ = leaveDays_;
        result.sex_ = sex_;
        result.adm_ = adm_;
        result.sep_ = sep_;
        result.gestage_ = gestage_;
        result.los_ = los_;
        result.hmv_ = hmv_;
        result.bh_ = bh_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Pc.PatientCase) {
          return mergeFrom((Pc.PatientCase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Pc.PatientCase other) {
        if (other == Pc.PatientCase.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getAgeYears() != 0) {
          setAgeYears(other.getAgeYears());
        }
        if (other.getAgeDays() != 0) {
          setAgeDays(other.getAgeDays());
        }
        if (other.getBirthDate() != 0) {
          setBirthDate(other.getBirthDate());
        }
        if (other.getAdmDate() != 0) {
          setAdmDate(other.getAdmDate());
        }
        if (other.getSepDate() != 0) {
          setSepDate(other.getSepDate());
        }
        if (other.getLeaveDays() != 0) {
          setLeaveDays(other.getLeaveDays());
        }
        if (!other.getSex().isEmpty()) {
          sex_ = other.sex_;
          onChanged();
        }
        if (!other.getAdm().isEmpty()) {
          adm_ = other.adm_;
          onChanged();
        }
        if (!other.getSep().isEmpty()) {
          sep_ = other.sep_;
          onChanged();
        }
        if (other.getGestage() != 0) {
          setGestage(other.getGestage());
        }
        if (other.getLos() != 0) {
          setLos(other.getLos());
        }
        if (other.getHmv() != 0) {
          setHmv(other.getHmv());
        }
        if (other.getBh() != false) {
          setBh(other.getBh());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Pc.PatientCase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Pc.PatientCase) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int ageYears_ ;
      /**
       * <code>int32 ageYears = 2;</code>
       * @return The ageYears.
       */
      @java.lang.Override
      public int getAgeYears() {
        return ageYears_;
      }
      /**
       * <code>int32 ageYears = 2;</code>
       * @param value The ageYears to set.
       * @return This builder for chaining.
       */
      public Builder setAgeYears(int value) {
        
        ageYears_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ageYears = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgeYears() {
        
        ageYears_ = 0;
        onChanged();
        return this;
      }

      private int ageDays_ ;
      /**
       * <code>int32 ageDays = 3;</code>
       * @return The ageDays.
       */
      @java.lang.Override
      public int getAgeDays() {
        return ageDays_;
      }
      /**
       * <code>int32 ageDays = 3;</code>
       * @param value The ageDays to set.
       * @return This builder for chaining.
       */
      public Builder setAgeDays(int value) {
        
        ageDays_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ageDays = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgeDays() {
        
        ageDays_ = 0;
        onChanged();
        return this;
      }

      private int birthDate_ ;
      /**
       * <code>uint32 birthDate = 4;</code>
       * @return The birthDate.
       */
      @java.lang.Override
      public int getBirthDate() {
        return birthDate_;
      }
      /**
       * <code>uint32 birthDate = 4;</code>
       * @param value The birthDate to set.
       * @return This builder for chaining.
       */
      public Builder setBirthDate(int value) {
        
        birthDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 birthDate = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBirthDate() {
        
        birthDate_ = 0;
        onChanged();
        return this;
      }

      private int admDate_ ;
      /**
       * <code>uint32 admDate = 5;</code>
       * @return The admDate.
       */
      @java.lang.Override
      public int getAdmDate() {
        return admDate_;
      }
      /**
       * <code>uint32 admDate = 5;</code>
       * @param value The admDate to set.
       * @return This builder for chaining.
       */
      public Builder setAdmDate(int value) {
        
        admDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 admDate = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAdmDate() {
        
        admDate_ = 0;
        onChanged();
        return this;
      }

      private int sepDate_ ;
      /**
       * <code>uint32 sepDate = 6;</code>
       * @return The sepDate.
       */
      @java.lang.Override
      public int getSepDate() {
        return sepDate_;
      }
      /**
       * <code>uint32 sepDate = 6;</code>
       * @param value The sepDate to set.
       * @return This builder for chaining.
       */
      public Builder setSepDate(int value) {
        
        sepDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sepDate = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSepDate() {
        
        sepDate_ = 0;
        onChanged();
        return this;
      }

      private int leaveDays_ ;
      /**
       * <code>int32 leaveDays = 7;</code>
       * @return The leaveDays.
       */
      @java.lang.Override
      public int getLeaveDays() {
        return leaveDays_;
      }
      /**
       * <code>int32 leaveDays = 7;</code>
       * @param value The leaveDays to set.
       * @return This builder for chaining.
       */
      public Builder setLeaveDays(int value) {
        
        leaveDays_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 leaveDays = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaveDays() {
        
        leaveDays_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sex_ = "";
      /**
       * <code>string sex = 8;</code>
       * @return The sex.
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sex = 8;</code>
       * @return The bytes for sex.
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sex = 8;</code>
       * @param value The sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {
        
        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 8;</code>
       * @param value The bytes for sex to set.
       * @return This builder for chaining.
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sex_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object adm_ = "";
      /**
       * <code>string adm = 9;</code>
       * @return The adm.
       */
      public java.lang.String getAdm() {
        java.lang.Object ref = adm_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          adm_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string adm = 9;</code>
       * @return The bytes for adm.
       */
      public com.google.protobuf.ByteString
          getAdmBytes() {
        java.lang.Object ref = adm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string adm = 9;</code>
       * @param value The adm to set.
       * @return This builder for chaining.
       */
      public Builder setAdm(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        adm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string adm = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearAdm() {
        
        adm_ = getDefaultInstance().getAdm();
        onChanged();
        return this;
      }
      /**
       * <code>string adm = 9;</code>
       * @param value The bytes for adm to set.
       * @return This builder for chaining.
       */
      public Builder setAdmBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        adm_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sep_ = "";
      /**
       * <code>string sep = 10;</code>
       * @return The sep.
       */
      public java.lang.String getSep() {
        java.lang.Object ref = sep_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sep_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sep = 10;</code>
       * @return The bytes for sep.
       */
      public com.google.protobuf.ByteString
          getSepBytes() {
        java.lang.Object ref = sep_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sep_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sep = 10;</code>
       * @param value The sep to set.
       * @return This builder for chaining.
       */
      public Builder setSep(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sep = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearSep() {
        
        sep_ = getDefaultInstance().getSep();
        onChanged();
        return this;
      }
      /**
       * <code>string sep = 10;</code>
       * @param value The bytes for sep to set.
       * @return This builder for chaining.
       */
      public Builder setSepBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sep_ = value;
        onChanged();
        return this;
      }

      private int gestage_ ;
      /**
       * <code>int32 gestage = 11;</code>
       * @return The gestage.
       */
      @java.lang.Override
      public int getGestage() {
        return gestage_;
      }
      /**
       * <code>int32 gestage = 11;</code>
       * @param value The gestage to set.
       * @return This builder for chaining.
       */
      public Builder setGestage(int value) {
        
        gestage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 gestage = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearGestage() {
        
        gestage_ = 0;
        onChanged();
        return this;
      }

      private int los_ ;
      /**
       * <code>int32 los = 12;</code>
       * @return The los.
       */
      @java.lang.Override
      public int getLos() {
        return los_;
      }
      /**
       * <code>int32 los = 12;</code>
       * @param value The los to set.
       * @return This builder for chaining.
       */
      public Builder setLos(int value) {
        
        los_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 los = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearLos() {
        
        los_ = 0;
        onChanged();
        return this;
      }

      private int hmv_ ;
      /**
       * <code>int32 hmv = 13;</code>
       * @return The hmv.
       */
      @java.lang.Override
      public int getHmv() {
        return hmv_;
      }
      /**
       * <code>int32 hmv = 13;</code>
       * @param value The hmv to set.
       * @return This builder for chaining.
       */
      public Builder setHmv(int value) {
        
        hmv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hmv = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearHmv() {
        
        hmv_ = 0;
        onChanged();
        return this;
      }

      private boolean bh_ ;
      /**
       * <code>bool bh = 14;</code>
       * @return The bh.
       */
      @java.lang.Override
      public boolean getBh() {
        return bh_;
      }
      /**
       * <code>bool bh = 14;</code>
       * @param value The bh to set.
       * @return This builder for chaining.
       */
      public Builder setBh(boolean value) {
        
        bh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool bh = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearBh() {
        
        bh_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PatientCase)
    }

    // @@protoc_insertion_point(class_scope:PatientCase)
    private static final Pc.PatientCase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Pc.PatientCase();
    }

    public static Pc.PatientCase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PatientCase>
        PARSER = new com.google.protobuf.AbstractParser<PatientCase>() {
      @java.lang.Override
      public PatientCase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PatientCase(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PatientCase> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PatientCase> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Pc.PatientCase getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string drg = 1;</code>
     * @return The drg.
     */
    java.lang.String getDrg();
    /**
     * <code>string drg = 1;</code>
     * @return The bytes for drg.
     */
    com.google.protobuf.ByteString
        getDrgBytes();

    /**
     * <code>string mdc = 2;</code>
     * @return The mdc.
     */
    java.lang.String getMdc();
    /**
     * <code>string mdc = 2;</code>
     * @return The bytes for mdc.
     */
    com.google.protobuf.ByteString
        getMdcBytes();

    /**
     * <code>uint32 pccl = 3;</code>
     * @return The pccl.
     */
    int getPccl();

    /**
     * <code>uint32 gst = 4;</code>
     * @return The gst.
     */
    int getGst();
  }
  /**
   * Protobuf type {@code Result}
   */
  public static final class Result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Result)
      ResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result() {
      drg_ = "";
      mdc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Result();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              drg_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              mdc_ = s;
              break;
            }
            case 24: {

              pccl_ = input.readUInt32();
              break;
            }
            case 32: {

              gst_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Pc.internal_static_Result_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Pc.internal_static_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Pc.Result.class, Pc.Result.Builder.class);
    }

    public static final int DRG_FIELD_NUMBER = 1;
    private volatile java.lang.Object drg_;
    /**
     * <code>string drg = 1;</code>
     * @return The drg.
     */
    @java.lang.Override
    public java.lang.String getDrg() {
      java.lang.Object ref = drg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        drg_ = s;
        return s;
      }
    }
    /**
     * <code>string drg = 1;</code>
     * @return The bytes for drg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDrgBytes() {
      java.lang.Object ref = drg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        drg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MDC_FIELD_NUMBER = 2;
    private volatile java.lang.Object mdc_;
    /**
     * <code>string mdc = 2;</code>
     * @return The mdc.
     */
    @java.lang.Override
    public java.lang.String getMdc() {
      java.lang.Object ref = mdc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mdc_ = s;
        return s;
      }
    }
    /**
     * <code>string mdc = 2;</code>
     * @return The bytes for mdc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMdcBytes() {
      java.lang.Object ref = mdc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mdc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PCCL_FIELD_NUMBER = 3;
    private int pccl_;
    /**
     * <code>uint32 pccl = 3;</code>
     * @return The pccl.
     */
    @java.lang.Override
    public int getPccl() {
      return pccl_;
    }

    public static final int GST_FIELD_NUMBER = 4;
    private int gst_;
    /**
     * <code>uint32 gst = 4;</code>
     * @return The gst.
     */
    @java.lang.Override
    public int getGst() {
      return gst_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDrgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, drg_);
      }
      if (!getMdcBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mdc_);
      }
      if (pccl_ != 0) {
        output.writeUInt32(3, pccl_);
      }
      if (gst_ != 0) {
        output.writeUInt32(4, gst_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDrgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, drg_);
      }
      if (!getMdcBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mdc_);
      }
      if (pccl_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, pccl_);
      }
      if (gst_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, gst_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Pc.Result)) {
        return super.equals(obj);
      }
      Pc.Result other = (Pc.Result) obj;

      if (!getDrg()
          .equals(other.getDrg())) return false;
      if (!getMdc()
          .equals(other.getMdc())) return false;
      if (getPccl()
          != other.getPccl()) return false;
      if (getGst()
          != other.getGst()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DRG_FIELD_NUMBER;
      hash = (53 * hash) + getDrg().hashCode();
      hash = (37 * hash) + MDC_FIELD_NUMBER;
      hash = (53 * hash) + getMdc().hashCode();
      hash = (37 * hash) + PCCL_FIELD_NUMBER;
      hash = (53 * hash) + getPccl();
      hash = (37 * hash) + GST_FIELD_NUMBER;
      hash = (53 * hash) + getGst();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Pc.Result parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pc.Result parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pc.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pc.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pc.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pc.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pc.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Pc.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Pc.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Pc.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Pc.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Pc.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Pc.Result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Result)
        Pc.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Pc.internal_static_Result_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Pc.internal_static_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Pc.Result.class, Pc.Result.Builder.class);
      }

      // Construct using Pc.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        drg_ = "";

        mdc_ = "";

        pccl_ = 0;

        gst_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Pc.internal_static_Result_descriptor;
      }

      @java.lang.Override
      public Pc.Result getDefaultInstanceForType() {
        return Pc.Result.getDefaultInstance();
      }

      @java.lang.Override
      public Pc.Result build() {
        Pc.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Pc.Result buildPartial() {
        Pc.Result result = new Pc.Result(this);
        result.drg_ = drg_;
        result.mdc_ = mdc_;
        result.pccl_ = pccl_;
        result.gst_ = gst_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Pc.Result) {
          return mergeFrom((Pc.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Pc.Result other) {
        if (other == Pc.Result.getDefaultInstance()) return this;
        if (!other.getDrg().isEmpty()) {
          drg_ = other.drg_;
          onChanged();
        }
        if (!other.getMdc().isEmpty()) {
          mdc_ = other.mdc_;
          onChanged();
        }
        if (other.getPccl() != 0) {
          setPccl(other.getPccl());
        }
        if (other.getGst() != 0) {
          setGst(other.getGst());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Pc.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Pc.Result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object drg_ = "";
      /**
       * <code>string drg = 1;</code>
       * @return The drg.
       */
      public java.lang.String getDrg() {
        java.lang.Object ref = drg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          drg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string drg = 1;</code>
       * @return The bytes for drg.
       */
      public com.google.protobuf.ByteString
          getDrgBytes() {
        java.lang.Object ref = drg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          drg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string drg = 1;</code>
       * @param value The drg to set.
       * @return This builder for chaining.
       */
      public Builder setDrg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        drg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string drg = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDrg() {
        
        drg_ = getDefaultInstance().getDrg();
        onChanged();
        return this;
      }
      /**
       * <code>string drg = 1;</code>
       * @param value The bytes for drg to set.
       * @return This builder for chaining.
       */
      public Builder setDrgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        drg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mdc_ = "";
      /**
       * <code>string mdc = 2;</code>
       * @return The mdc.
       */
      public java.lang.String getMdc() {
        java.lang.Object ref = mdc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mdc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mdc = 2;</code>
       * @return The bytes for mdc.
       */
      public com.google.protobuf.ByteString
          getMdcBytes() {
        java.lang.Object ref = mdc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mdc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mdc = 2;</code>
       * @param value The mdc to set.
       * @return This builder for chaining.
       */
      public Builder setMdc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mdc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mdc = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMdc() {
        
        mdc_ = getDefaultInstance().getMdc();
        onChanged();
        return this;
      }
      /**
       * <code>string mdc = 2;</code>
       * @param value The bytes for mdc to set.
       * @return This builder for chaining.
       */
      public Builder setMdcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mdc_ = value;
        onChanged();
        return this;
      }

      private int pccl_ ;
      /**
       * <code>uint32 pccl = 3;</code>
       * @return The pccl.
       */
      @java.lang.Override
      public int getPccl() {
        return pccl_;
      }
      /**
       * <code>uint32 pccl = 3;</code>
       * @param value The pccl to set.
       * @return This builder for chaining.
       */
      public Builder setPccl(int value) {
        
        pccl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 pccl = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPccl() {
        
        pccl_ = 0;
        onChanged();
        return this;
      }

      private int gst_ ;
      /**
       * <code>uint32 gst = 4;</code>
       * @return The gst.
       */
      @java.lang.Override
      public int getGst() {
        return gst_;
      }
      /**
       * <code>uint32 gst = 4;</code>
       * @param value The gst to set.
       * @return This builder for chaining.
       */
      public Builder setGst(int value) {
        
        gst_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 gst = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGst() {
        
        gst_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Result)
    }

    // @@protoc_insertion_point(class_scope:Result)
    private static final Pc.Result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Pc.Result();
    }

    public static Pc.Result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result>
        PARSER = new com.google.protobuf.AbstractParser<Result>() {
      @java.lang.Override
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Pc.Result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientCase_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientCase_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014res/pc.proto\"\342\001\n\013PatientCase\022\n\n\002id\030\001 \001" +
      "(\t\022\020\n\010ageYears\030\002 \001(\005\022\017\n\007ageDays\030\003 \001(\005\022\021\n" +
      "\tbirthDate\030\004 \001(\r\022\017\n\007admDate\030\005 \001(\r\022\017\n\007sep" +
      "Date\030\006 \001(\r\022\021\n\tleaveDays\030\007 \001(\005\022\013\n\003sex\030\010 \001" +
      "(\t\022\013\n\003adm\030\t \001(\t\022\013\n\003sep\030\n \001(\t\022\017\n\007gestage\030" +
      "\013 \001(\005\022\013\n\003los\030\014 \001(\005\022\013\n\003hmv\030\r \001(\005\022\n\n\002bh\030\016 " +
      "\001(\010\"=\n\006Result\022\013\n\003drg\030\001 \001(\t\022\013\n\003mdc\030\002 \001(\t\022" +
      "\014\n\004pccl\030\003 \001(\r\022\013\n\003gst\030\004 \001(\rb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PatientCase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PatientCase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientCase_descriptor,
        new java.lang.String[] { "Id", "AgeYears", "AgeDays", "BirthDate", "AdmDate", "SepDate", "LeaveDays", "Sex", "Adm", "Sep", "Gestage", "Los", "Hmv", "Bh", });
    internal_static_Result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Result_descriptor,
        new java.lang.String[] { "Drg", "Mdc", "Pccl", "Gst", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
